version: "3"
services:
  influxdb:
    image: influxdb:2.7.1
    container_name: influxdb
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=1234qwer
      - DOCKER_INFLUXDB_INIT_ORG=smms
      - DOCKER_INFLUXDB_INIT_BUCKET=default
      # - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=UCKlJPxsB8n0NSqnrKOJahQitAoxtT9Iie2T3Y49CD2JZCz68-717av9HoEAT1Uo87n_O0c5WdELtEeCK6PpVQ==
    volumes:
      - ~/influxdb/data:/var/lib/influxdb2
      - ~/influxdb/config:/etc/influxdb2
    ports:
      - "127.0.0.1:8086:8086"
